# Generated by Django 4.0.3 on 2022-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(unique=True)),
                ('name_of_exam', models.CharField(default='examination', max_length=100)),
                ('age_limit', models.IntegerField(verbose_name='age limit')),
                ('required_subjects', models.CharField(max_length=1000)),
                ('percentage_crietria', models.IntegerField()),
                ('suggested_study_material', models.CharField(max_length=100)),
                ('cut_off', models.IntegerField(max_length=3)),
                ('more_details', models.CharField(max_length=10000)),
                ('official_website', models.URLField()),
                ('registration_link', models.URLField()),
                ('source', models.CharField(max_length=1000, verbose_name='cource of info.')),
            ],
        ),
    ]
