# Generated by Django 4.0.3 on 2022-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='percentage_crietria',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
