# Generated by Django 4.0.3 on 2022-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_suggested_study_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cut_off',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='more_details',
            field=models.CharField(max_length=100000),
        ),
    ]
